import type { Metadata } from 'next';
import logo from '@public/icons/logo.png';
import Image from 'next/image';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className=''>
      <Image className='w-67 h-32' src={logo} alt='logo' />
      {children}
    </div>
  );
}
