import type { Metadata } from 'next';
import logo from '@public/icons/logo.png';
import Image from 'next/image';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className='flex flex-col h-svh justify-center items-center'>
      <div className='absolute top-0 w-360 h-56 px-16 py-12'>
        <Image className='object-contain' width={67.63} height={32} src={logo} alt='logo' />
      </div>
      <div className='w-full px-32'>{children}</div>
    </div>
  );
}
