import type { Metadata } from 'next';
import '../../styles/globals.css';
import Navigation from '@/components/organisms/navigation/navigation/Navigation';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function SocialLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className='flex justify-center'>
      <main id='modal' className='flex flex-col items-center  relative  w-fit '>
        <header className='w-full mb-76'>
          <Navigation />
        </header>
        {children}
      </main>
    </div>
  );
}
